### ISSUE TITLE
MockiEbean with ebean13

### ISSUE THREAD

**Issue by nPraml** [ebean-orm/ebean-mocker#22]
Hello @rbygrave ,

we are using now MockiEbean with ebean13 and we get a `NoSuchMethodError` for `getName()` in `MockiEbean`, in the method `restoreOriginal()` at line 201. 
It should be `original.name()`, the same for line 206.

Can you please fix it?

Kind regards,
Noemi

**Comment by rPraml** [comment]
Hello @rbygrave,

we are currently a bit blocked by this issue. The problem is, that ebean-mocker is not yet compatible with ebean 13.

do you have time to fix this in the next days or should we fork the project

**Comment by rbygrave** [comment]
Best if you fork and submit a PR to fix it.

**Comment by nPraml** [comment]
I opened a PR and I have one question to the last compile error, see https://github.com/ebean-orm/ebean-mocker/pull/23

**Comment by rbygrave** [comment]
Refer related PR in Ebean - https://github.com/ebean-orm/ebean/pull/2675 ... to make DefaultOrmQuery non final.
